---
version: '3'

services:
  nextcloud_db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - "MYSQL_PASSWORD=__db_password__"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud_app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - nextcloud_db
    volumes:
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    restart: always
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - "MYSQL_PASSWORD=__db_password__"
      - MYSQL_HOST=nextcloud_db
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
