version: '3'

services:
  nextcloud_db:
    image: mariadb
    restart: always
    volumes:
      - ./var/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=__db_password__
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud_app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - nextcloud_db
    volumes:
      - ./var/config:/var/www/html/config
      - ./var/data:/var/www/html/data
    restart: always
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=__db_password__
      - MYSQL_HOST=nextcloud_db
      - NEXTCLOUD_ADMIN_USER=__nextcloud_admin__
      - NEXTCLOUD_ADMIN_PASSWORD=__nextcloud_password__
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
